client: client.cpp ../Library/server.cpp ../Library/client.cpp ../Library/socketwrappers.cpp ../Library/library.cpp
	g++ -g -Wall -o client client.cpp ../Library/server.cpp ../Library/client.cpp ../Library/socketwrappers.cpp ../Library/library.cpp
