emulator: emulator.cpp ../Library/library.cpp  ../Library/server.cpp ../Library/client.cpp ../Library/socketwrappers.cpp
	g++ -g -Wall -o emulator emulator.cpp ../Library/library.cpp  ../Library/server.cpp ../Library/client.cpp ../Library/socketwrappers.cpp
